# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-10-24 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('park1', '0002_auto_20181024_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park1',
            name='park_id',
            field=models.CharField(default=uuid.uuid1, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='park1',
            name='park_name',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
