# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-10-25 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park1', '0003_auto_20181024_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park1',
            name='park_id',
            field=models.CharField(default='e637a4c4d84711e8ae70000c29ca37dd', max_length=200, primary_key=True, serialize=False),
        ),
    ]
