# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-10-26 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park1', '0005_auto_20181025_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park1',
            name='park_id',
            field=models.CharField(default='0e6a0f63d8c611e8bb87000c29ca37dd', max_length=32, primary_key=True, serialize=False),
        ),
    ]
